### ISSUE TITLE
Remove target name mangling

### ISSUE THREAD

**Issue by camillescott** [cboursnell/crb-blast#7]
The target name appears to be mangled during output, where it is split on pipes and only the first token used. This breaks on many databases; for example, uniprot sequences are formatted <type>|<uniprot_id>|<db_id> (or something to that effect), and with this system all you get is <type> (which is often just "tr" or "sp" or something equally uninformative).

**Comment by Blahah** [comment]
We take the `entry_id` because BLAST mangles names itself, and if we don't do it ourselves we can't match up the results. 

However, we're doing it wrong [here](https://github.com/cboursnell/crb-blast/blob/master/lib/crb-blast/hit.rb#L11-L12). We should be using the BioFastaFormat defline parser from BioRuby to parse out the `entry_id`. It's still not perfect because of the knock-on effects of the great NCBI FASTA format controversy, but it handles the commonest cases.

**Comment by Blahah** [comment]
@camillescott do you have some example deflines we can use for a regression test?

**Comment by camillescott** [comment]
Really any non-NCBI defline with a pipe in it. Here are some uniprot ones from one of my databases:

tr|C3Y8C9|C3Y8C9_BRAFL
sp|O47426|ATP6_BRAFL
sp|C4A0D9|BAP1_BRAFL
